name: Windows

on:
  pull_request:
  push:
    branches:
      - dev
      - release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-windows:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true
      - name: Restore cached OpenCV source
        uses: actions/cache/restore@v4
        id: cache-opencv-source
        with:
          key: opencv-source-410-windows-v1a
          path: |
            ./opencv/opencv-4.10.0
            ./opencv/opencv_contrib-4.10.0
      - name: Download OpenCV source
        if: steps.cache-opencv-source.outputs.cache-hit != 'true'
        shell: bash
        run: |
            mkdir -p ./opencv
            curl -Lo ./opencv/opencv-4.10.0.zip https://github.com/opencv/opencv/archive/4.10.0.zip
            curl -Lo ./opencv/opencv_contrib-4.10.0.zip https://github.com/opencv/opencv_contrib/archive/4.10.0.zip
      - name: Extract OpenCV source
        if: steps.cache-opencv-source.outputs.cache-hit != 'true'
        shell: bash
        run: |
            cd ./opencv
            mkdir -p opencv-4.10.0
            mkdir -p opencv_contrib-4.10.0
            7z x opencv-4.10.0.zip
            7z x opencv_contrib-4.10.0.zip
      - name: Save cached OpenCV source
        uses: actions/cache/save@v4
        if: steps.cache-opencv-source.outputs.cache-hit != 'true'
        with:
          key: ${{ steps.cache-opencv-source.outputs.cache-primary-key }}
          path: |
            ./opencv/opencv-4.10.0
            ./opencv/opencv_contrib-4.10.0
      - name: Restore cached OpenCV build
        uses: actions/cache/restore@v4
        id: cache-opencv-build
        with:
          key: opencv-build-410-windows-v1d
          path: |
            ./opencv/build
      - name: Build OpenCV
        if: steps.cache-opencv-build.outputs.cache-hit != 'true'
        run: |
            mkdir -p ./opencv/build            
            cd ./opencv/build
            cmake -G "MinGW Makefiles" -DENABLE_CXX11=ON -DOPENCV_EXTRA_MODULES_PATH="../opencv_contrib-4.10.0/modules" -DBUILD_SHARED_LIBS=ON -DWITH_IPP=OFF -DWITH_MSMF=OFF -DBUILD_EXAMPLES=OFF -DBUILD_TESTS=OFF -DBUILD_PERF_TESTS=ON -DBUILD_opencv_java=OFF -DBUILD_opencv_python=OFF -DBUILD_opencv_python2=OFF -DBUILD_opencv_python3=OFF -DBUILD_DOCS=OFF -DENABLE_PRECOMPILED_HEADERS=OFF -DBUILD_opencv_saliency=OFF -DBUILD_opencv_wechat_qrcode=ON -DCPU_DISPATCH= -DOPENCV_GENERATE_PKGCONFIG=ON -DWITH_OPENCL_D3D11_NV=OFF -DOPENCV_ALLOCATOR_STATS_COUNTER_TYPE=int64_t -DOPENCV_ENABLE_NONFREE=ON -Wno-dev ../opencv-4.10.0
            cmake --build . --target install
      - name: Save cached OpenCV build
        uses: actions/cache/save@v4
        if: steps.cache-opencv-build.outputs.cache-hit != 'true'
        with:
          key: ${{ steps.cache-opencv-build.outputs.cache-primary-key }}
          path: |
            ./opencv/build
      - name: Set GoCV env
        run: |
            go env
            echo "CGO_CXXFLAGS=--std=c++11" >> $env:GITHUB_ENV
            echo "CGO_CPPFLAGS=-I${env:GITHUB_WORKSPACE}\opencv\build\install\include" >> $env:GITHUB_ENV
            echo "CGO_LDFLAGS=-L${env:GITHUB_WORKSPACE}\opencv\build\install\x64\mingw\lib -lopencv_core410 -lopencv_face410 -lopencv_videoio410 -lopencv_imgproc410 -lopencv_highgui410 -lopencv_imgcodecs410 -lopencv_objdetect410 -lopencv_features2d410 -lopencv_video410 -lopencv_dnn410 -lopencv_xfeatures2d410 -lopencv_plot410 -lopencv_tracking410 -lopencv_img_hash410 -lopencv_calib3d410 -lopencv_bgsegm410 -lopencv_photo410 -lopencv_aruco410 -lopencv_wechat_qrcode410 -lopencv_ximgproc410 -lopencv_xphoto410" >> $env:GITHUB_ENV
            echo "${env:GITHUB_WORKSPACE}/opencv/build/install/x64/mingw/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - name: Test GoCV
        run: |
            go env
            go test -v -tags="matprofile,customenv" .
      - name: Test GoCV Contrib
        run: |
            go test -v -tags="matprofile,customenv" ./contrib
